popularStocks = [
    ["AMZN", "Amazon"],
    ["MSFT", "Microsoft"],
    ["HOOD", "Robinhood Markets"],
    ["WMT", "Walmart"],
    ["CPRX", "Catalyst Pharmaceuticals"],
    ["TSLA", "Tesla"],
    ["AAPL", "Apple"],
    ["F", "Ford Motor"],
    ["AMC", "AMC Entertainment"],
    ["APE", "AMC Entertainment, Preferred Equity Units"],
    ["SNDL", "SNDL"],
    ["DIS", "Disney"],
    ["NIO", "NIO"],
    ["META", "Meta Platforms"],
    ["LCID", "Lucid Group"],
    ["VOO", "Vanguard S&P 500 ETF"],
    ["NFLX", "Netflix"],
    ["NVDA", "NVIDIA"],
    ["SPY", "SPDR S&P 500 ETF"],
    ["GOOGL", "Alphabet Class A"],
    ["SNAP", "Snap"],
    ["GPRO", "GoPro"],
    ["PFE", "Pfizer"],
    ["PLUG", "Plug Power"],
    ["BABA", "Alibaba"],
    ["CCL", "Carnival"],
    ["AAL", "American Airlines"],
    ["BAC", "Bank of America"],
    ["RIVN", "Rivian Automotive"],
    ["SBUX", "Starbucks"],
    ["VTI", "Vanguard Total Stock Market ETF"],
    ["PLTR", "Palantir Technologies"],
    ["DAL", "Delta Air Lines"],
    ["AMD", "AMD"],
    ["KO", "Coca-Cola"],
    ["NOK", "Nokia"],
    ["GME", "GameStop"],
    ["TLRY", "Tilray Brands"],
    ["COIN", "Coinbase"],
    ["T", "AT&T"],
    ["CGC", "Canopy Growth"],
    ["PYPL", "PayPal"],
    ["SPCE", "Virgin Galactic Holdings"],
    ["UBER", "Uber"],
    ["GM", "GM"],
    ["BB", "Blackberry"],
    ["FCEL", "FuelCell Energy"],
    ["MRNA", "Moderna"],
    ["GE", "GE"],
    ["VWO", "Vanguard FTSE Emerging Markets Fund"],
    ["PSEC", "Prospect Capital"],
    ["QQQ", "Invesco QQQ"],
    ["RBLX", "Roblox"],
    ["SQ", "Block"],
    ["VEA", "Vanguard FTSE Developed Markets ETF"],
    ["NCLH", "Norwegian Cruise Line"],
    ["BND", "Vanguard Total Bond Market ETF"],
    ["ABNB", "Airbnb"],
    ["BA", "Boeing"],
    ["DKNG", "DraftKings"],
    ["CRON", "Cronos Group"],
    ["CHPT", "ChargePoint"],
    ["NKLA", "Nikola"],
    ["SIRI", "Sirius XM"],
    ["JNJ", "Johnson & Johnson"],
    ["XOM", "Exxon Mobil"],
    ["UAL", "United Airlines"],
    ["INTC", "Intel"],
    ["LUV", "Southwest Airlines"],
    ["GOOG", "Alphabet Class C"],
    ["NKE", "Nike"],
    ["SOFI", "SoFi Technologies"],
    ["ARKK", "ARK Innovation ETF"],
    ["RIOT", "Riot Platforms"],
    ["MRO", "Marathon Oil"],
    ["DWAC", "Digital World Acquisition"],
    ["PTON", "Peloton Interactive"],
    ["COST", "Costco"],
    ["ET", "Energy Transfer"],
    ["JBLU", "JetBlue Airways"],
    ["SHOP", "Shopify"],
    ["TSM", "Taiwan Semiconductor Manufacturing"],
    ["BRK.B", "Berkshire Hathaway"],
    ["JPM", "JPMorgan Chase"],
    ["BNGO", "Bionano Genomics"],
    ["SONY", "Sony"],
    ["O", "Realty Income"],
    ["V", "Visa"],
    ["IVV", "iShares Core S&P 500 ETF"],
    ["RCL", "Royal Caribbean Group"],
    ["RYCEY", "Rolls-Royce"],
    ["TGT", "Target"],
    ["VYM", "Vanguard High Dividend Yield ETF"],
    ["SPHD", "Invesco S&P 500 High Dividend Low Volatility ETF"],
    ["CLOV", "Clover Health Investments"],
    ["RITM", "Rithm Capital"],
    ["ZM", "Zoom"],
    ["VZ", "Verizon"],
    ["CRM", "Salesforce"],
    ["SPYG", "SPDR Portfolio S&P 500 Growth ETF"],
]
